// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuMrBgm9EQ9nwepS6RW6XEEx_bwihOd-g',
    appId: '1:132164332635:web:9080be7b9c073f37b1e37e',
    messagingSenderId: '132164332635',
    projectId: 'gabmed-bdc16',
    authDomain: 'gabmed-bdc16.firebaseapp.com',
    storageBucket: 'gabmed-bdc16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9OZ1MRboM6KvmgJFcXKaMyPUs2Pyd368',
    appId: '1:132164332635:android:c36afff403f27e7db1e37e',
    messagingSenderId: '132164332635',
    projectId: 'gabmed-bdc16',
    storageBucket: 'gabmed-bdc16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBazUgrbI-8BhPXW7W5uAGW1EcX0AOcEZg',
    appId: '1:132164332635:ios:ba956db2bbad095eb1e37e',
    messagingSenderId: '132164332635',
    projectId: 'gabmed-bdc16',
    storageBucket: 'gabmed-bdc16.appspot.com',
    iosBundleId: 'com.example.gm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBazUgrbI-8BhPXW7W5uAGW1EcX0AOcEZg',
    appId: '1:132164332635:ios:ba956db2bbad095eb1e37e',
    messagingSenderId: '132164332635',
    projectId: 'gabmed-bdc16',
    storageBucket: 'gabmed-bdc16.appspot.com',
    iosBundleId: 'com.example.gm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuMrBgm9EQ9nwepS6RW6XEEx_bwihOd-g',
    appId: '1:132164332635:web:c97afce46eed6e8db1e37e',
    messagingSenderId: '132164332635',
    projectId: 'gabmed-bdc16',
    authDomain: 'gabmed-bdc16.firebaseapp.com',
    storageBucket: 'gabmed-bdc16.appspot.com',
  );
}
